name: GitHub Release Drafter

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Release version'
      publish:
        description: 'Enable publish release?'
        required: true
        default: 'false'
        type: string
      config-name:
        description: 'Release Drafter configuration file'
        required: false
        default: 'release-drafter-config.yml'
        type: string

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Release version: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Enable publish release: ${{ inputs.publish }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version env
        run: echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ inputs.config-name }}
          publish: ${{ inputs.publish }}
          name: ${{ env.RELEASE_VERSION }}
          tag: v${{ env.RELEASE_VERSION }}
          version: v${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
